version: "3"

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}

  src:
    depends_on:
      - db
    build: .
    working_dir: /app
    container_name: "src_camp_container"
    volumes:
      - ./app/:/app
    ports:
      - "8000:8080"
    restart: on-failure:10
    #Actualizacion e instalacion
    command: bash -c "alembic revision --autogenerate && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
    #Solo instalacion
    #command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
